CREATE TABLE conta (
    id BIGSERIAL PRIMARY KEY,
    usuario_id BIGINT UNIQUE NOT NULL,
    saldo BIGINT NOT NULL DEFAULT 0,
    ult_atu TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE RESTRICT
);